version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=food_project.settings
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=food_storage_db
      - POSTGRES_USER=food_user
      - POSTGRES_PASSWORD=food_password
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
