# Generated by Django 5.2.1 on 2025-05-25 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='best_before',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
