# Generated by Django 5.2.1 on 2025-05-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_food_best_before_food_category_alter_food_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ideal_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
