# Generated by Django 5.2.1 on 2025-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_alter_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Litres'), ('ml', 'Millilitres'), ('packs', 'Packs')], default='packs', max_length=10),
        ),
    ]
