# Generated by Django 5.2.1 on 2025-06-10 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_food_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="best_before",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
