name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install Flake8
        run: pip install flake8
      - name: Run Flake8
        run: flake8 food_project/

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r food_project/requirements.txt
      - name: Run tests
        run: python food_project/manage.py test

  docker_build:
    runs-on: ubuntu-latest
    needs: build # Depends on the test job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./food_project # Path to the directory containing Dockerfile and app code
          file: ./food_project/Dockerfile.prod # Path to the production Dockerfile
          push: false # We are only building, not pushing to a registry
          tags: django-food-project:latest
